name: docker

on:
  push:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: docker build . -t jenkins-to-github-notify

    - name: Run tests
      run: docker run jenkins-to-github-notify pytest --color=yes
