name: docker

on:
  push:
    - master
  pull_request:

permissions:
  contents: read

# Cancel running jobs for the same branch and workflow.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build image
      run: docker build . -t jenkins-to-github-notify

    - name: Run tests
      run: docker run jenkins-to-github-notify pytest --color=yes
